import os
import logging
from typing import Dict, Any

from graph.state import ProjectState
from schemas.database import DatabaseArtifacts
from db.database import SessionLocal
from db.models import AgentOutput, RunEvent, ProjectRun

logger = logging.getLogger(__name__)


def generate_mock_db_artifacts(architecture: Dict, requirement: str) -> Dict[str, Any]:
    """
    Generates SQL migration scripts and seed data from the architecture DB schema.
    """
    req_lower = requirement.lower()
    is_task_app = "task" in req_lower or "todo" in req_lower

    if is_task_app:
        migration_sql = """\
-- 001_initial_schema.sql
-- Generated by ASDT Database Engineer Agent

CREATE TABLE IF NOT EXISTS tasks (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title       VARCHAR(100) NOT NULL,
    description TEXT,
    priority    VARCHAR(10)  NOT NULL DEFAULT 'Medium',
    status      VARCHAR(20)  NOT NULL DEFAULT 'Pending',
    tags        VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tasks_status   ON tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks (priority);
"""
        seed_sql = """\
-- seed_data.sql
-- Sample seed data for the TaskFlow application

INSERT INTO tasks (title, description, priority, status, tags) VALUES
    ('Set up project structure',   'Create the initial repo and configure build tools.', 'High',   'Completed',   'setup,devops'),
    ('Implement task CRUD API',    'Build FastAPI endpoints for task management.',        'High',   'In Progress', 'backend,api'),
    ('Design dashboard UI',        'Create the React dashboard with dark mode.',          'High',   'Pending',     'frontend,ux'),
    ('Write database migrations',  'Create SQL migration scripts for all tables.',        'Medium', 'Pending',     'database'),
    ('Add authentication',         'Implement JWT-based user authentication.',            'Medium', 'Pending',     'security,backend'),
    ('Write unit tests',           'Cover all API endpoints with pytest tests.',          'Low',    'Pending',     'testing');
"""
        alembic_ini = """\
[alembic]
script_location = alembic
sqlalchemy.url = sqlite:///./app.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = [sys.stderr]
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""
        alembic_env = """\
from logging.config import fileConfig
from sqlalchemy import engine_from_config, pool
from alembic import context
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from models import Base

config = context.config
if config.config_file_name:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

def run_migrations_offline():
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()

def run_migrations_online():
    connectable = engine_from_config(config.get_section(config.config_ini_section),
                                     prefix="sqlalchemy.", poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
"""
    else:
        migration_sql = """\
-- 001_initial_schema.sql
CREATE TABLE IF NOT EXISTS items (
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL
);
"""
        seed_sql = """\
-- seed_data.sql
INSERT INTO items (name) VALUES ('Sample Item 1'), ('Sample Item 2');
"""
        alembic_ini = "[alembic]\nscript_location = alembic\nsqlalchemy.url = sqlite:///./app.db\n"
        alembic_env = "# Alembic env.py placeholder"

    files = [
        {"path": "migrations/001_initial_schema.sql", "content": migration_sql},
        {"path": "seed/seed_data.sql",                "content": seed_sql},
        {"path": "alembic.ini",                       "content": alembic_ini},
        {"path": "alembic/env.py",                    "content": alembic_env},
        {"path": "README.md",                         "content": (
            "# Database\n\n"
            "## Apply Migrations\n```bash\nalembic upgrade head\n```\n\n"
            "## Run Seed Data\n```bash\nsqlite3 app.db < seed/seed_data.sql\n```\n"
        )},
    ]

    return {
        "files": files,
        "migration_tool": "Alembic",
        "apply_command": "alembic upgrade head"
    }


def database_node(state: ProjectState) -> Dict[str, Any]:
    """
    Database Engineer Agent Node.

    Input:
        - architecture_spec (dict): DB schema outline from Architect.

    Output:
        - db_migrations_path (str): Path to generated migration scripts on disk.

    Failure Mode:
        - Raises ValueError if architecture_spec is missing.
    """
    run_id = state.get("run_id")
    architecture = state.get("architecture_spec")
    requirement = state.get("business_requirement", "")

    if not architecture:
        raise ValueError("architecture_spec is missing. Architect node must run first.")

    db = SessionLocal()
    db.add(RunEvent(run_id=run_id, agent_name="Database Engineer", status="STARTED",
                    message="Database Engineer Agent starting SQL migration generation."))
    db.commit()

    db_data = None
    api_key = os.getenv("ANTHROPIC_API_KEY")
    is_mock = not api_key or api_key.startswith("your-")

    if not is_mock:
        try:
            from langchain_anthropic import ChatAnthropic
            llm = ChatAnthropic(model="claude-3-5-sonnet-20240620", temperature=0)
            structured_llm = llm.with_structured_output(DatabaseArtifacts)
            result = structured_llm.invoke(
                f"You are the Database Engineer Agent. Generate SQL migration scripts, seed data, "
                f"and Alembic config based on this DB schema.\n\nArchitecture: {architecture}"
            )
            db_data = result.dict()
        except Exception as e:
            logger.error(f"DB Engineer LLM failed, using mock: {e}")

    if db_data is None:
        db_data = generate_mock_db_artifacts(architecture, requirement)

    # Write files to disk
    output_dir = os.path.join("generated_projects", run_id, "db")
    for file_info in db_data["files"]:
        file_path = os.path.join(output_dir, file_info["path"])
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(file_info["content"])

    try:
        db.add(AgentOutput(run_id=run_id, agent_name="Database Engineer",
                           artifact_type="db_migrations",
                           content={"path": output_dir,
                                    "files": [f["path"] for f in db_data["files"]],
                                    "migration_tool": db_data["migration_tool"],
                                    "apply_command": db_data["apply_command"]}))
        db.add(RunEvent(run_id=run_id, agent_name="Database Engineer", status="COMPLETED",
                        message=f"Generated {len(db_data['files'])} DB artifact files in {output_dir}"))
        run_rec = db.query(ProjectRun).filter(ProjectRun.id == run_id).first()
        if run_rec:
            run_rec.current_agent = "Database Engineer"
        db.commit()
    except Exception as e:
        db.rollback()
        raise e
    finally:
        db.close()

    return {"db_migrations_path": output_dir}
