import os
import logging
from typing import Dict, Any

from graph.state import ProjectState
from schemas.devops import DevOpsManifests
from db.database import SessionLocal
from db.models import AgentOutput, RunEvent, ProjectRun

logger = logging.getLogger(__name__)


def generate_mock_devops_manifests(requirement: str) -> Dict[str, Any]:
    """
    Generates simulated Docker, Docker Compose, and Kubernetes configuration files.
    """
    dockerfile_backend = """\
# Dockerfile.backend
# Generated by ASDT DevOps Engineer Agent

FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
"""

    dockerfile_frontend = """\
# Dockerfile.frontend
# Generated by ASDT DevOps Engineer Agent

# Stage 1: Build React App
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
"""

    nginx_conf = """\
server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
"""

    docker_compose = """\
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    volumes:
      - backend_data:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_data:
"""

    k8s_deployment = """\
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend
  labels:
    app: taskflow-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-backend
  template:
    metadata:
      labels:
        app: taskflow-backend
    spec:
      containers:
      - name: backend
        image: taskflow-backend:latest
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "sqlite:///./app.db"
---
apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend-service
spec:
  selector:
    app: taskflow-backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
  labels:
    app: taskflow-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
    spec:
      containers:
      - name: frontend
        image: taskflow-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taskflow-frontend-service
spec:
  selector:
    app: taskflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
"""

    files = [
        {"path": "backend/Dockerfile.backend",   "content": dockerfile_backend},
        {"path": "frontend/Dockerfile.frontend", "content": dockerfile_frontend},
        {"path": "frontend/nginx.conf",          "content": nginx_conf},
        {"path": "docker-compose.yml",           "content": docker_compose},
        {"path": "k8s/deployment.yaml",          "content": k8s_deployment},
    ]

    return {
        "files": files,
        "container_tech": "Docker",
        "orchestration_tech": "Kubernetes"
    }


def devops_node(state: ProjectState) -> Dict[str, Any]:
    """
    DevOps Engineer Agent Node.

    Input:
        - qa_results (dict): Verification that tests passed.
        - security_report (dict): Verification that security check is clean.

    Output:
        - deployment_manifests (dict): Docker configuration, deployment manifests.
    """
    run_id = state.get("run_id")
    qa_res = state.get("qa_results")
    sec_rep = state.get("security_report")
    requirement = state.get("business_requirement", "")

    if not qa_res or not sec_rep:
        raise ValueError("qa_results and security_report are required. QA and Security nodes must run first.")

    db = SessionLocal()
    db.add(RunEvent(run_id=run_id, agent_name="DevOps Engineer", status="STARTED",
                    message="DevOps Engineer starting containerization and Kubernetes manifest generation."))
    db.commit()

    devops_data = None
    api_key = os.getenv("ANTHROPIC_API_KEY")
    is_mock = not api_key or api_key.startswith("your-")

    if not is_mock:
        try:
            from langchain_anthropic import ChatAnthropic
            llm = ChatAnthropic(model="claude-3-5-sonnet-20240620", temperature=0)
            structured_llm = llm.with_structured_output(DevOpsManifests)
            result = structured_llm.invoke(
                f"You are the DevOps Engineer Agent. Generate Dockerfiles, docker-compose.yml, "
                f"and Kubernetes deployment/service manifests based on this requirement: {requirement}"
            )
            devops_data = result.dict()
        except Exception as e:
            logger.error(f"DevOps Agent LLM failed, using mock: {e}")

    if devops_data is None:
        devops_data = generate_mock_devops_manifests(requirement)

    # Write files to disk under generated_projects/{run_id}/devops
    output_dir = os.path.join("generated_projects", run_id, "devops")
    for file_info in devops_data["files"]:
        file_path = os.path.join(output_dir, file_info["path"])
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(file_info["content"])

    try:
        db.add(AgentOutput(run_id=run_id, agent_name="DevOps Engineer",
                           artifact_type="deployment_manifests",
                           content={"path": output_dir,
                                    "files": [f["path"] for f in devops_data["files"]],
                                    "container_tech": devops_data["container_tech"],
                                    "orchestration_tech": devops_data["orchestration_tech"]}))
        db.add(RunEvent(run_id=run_id, agent_name="DevOps Engineer", status="COMPLETED",
                        message=f"Generated {len(devops_data['files'])} DevOps config files in {output_dir}"))
        run_rec = db.query(ProjectRun).filter(ProjectRun.id == run_id).first()
        if run_rec:
            run_rec.current_agent = "DevOps Engineer"
        db.commit()
    except Exception as e:
        db.rollback()
        raise e
    finally:
        db.close()

    return {"deployment_manifests": devops_data}
