import os
import json
import logging
from typing import Dict, Any

from graph.state import ProjectState
from schemas.documentation import ApiDocs
from db.database import SessionLocal
from db.models import AgentOutput, RunEvent, ProjectRun

logger = logging.getLogger(__name__)


def generate_mock_docs(requirement: str) -> Dict[str, Any]:
    """
    Generates simulated system README, OpenAPI specification, and Architecture Decision Record (ADR).
    """
    readme_md = f"""# Project TaskFlow

Generated by ASDT (Autonomous Software Development Team).
Requirement: "{requirement}"

## Tech Stack
- **Frontend**: React + Vite (Port 3000)
- **Backend**: FastAPI + SQLAlchemy ORM (Port 8001)
- **Database**: SQLite / PostgreSQL
- **Deployment**: Docker, Docker Compose, Kubernetes

## Local Development Setup

### Prereqs
- Node.js >= 18
- Python >= 3.10

### Steps
1. Run backend migrations:
   ```bash
   cd db
   sqlite3 ../backend/app.db < migrations/001_initial_schema.sql
   ```
2. Start the Backend server:
   ```bash
   cd backend
   pip install -r requirements.txt
   uvicorn main:app --reload --port 8001
   ```
3. Start the Frontend app:
   ```bash
   cd frontend
   npm install
   npm run dev
   ```

## Production Deployment
To build and run using Docker Compose:
```bash
docker-compose up --build
```
"""

    openapi_json = json.dumps({
        "openapi": "3.1.0",
        "info": {
            "title": "TaskFlow API",
            "version": "0.1.0",
            "description": "Backend API for task management."
        },
        "paths": {
            "/tasks/": {
                "get": {
                    "summary": "List Tasks",
                    "operationId": "list_tasks",
                    "responses": {
                        "200": {
                            "description": "Successful Response"
                        }
                    }
                },
                "post": {
                    "summary": "Create Task",
                    "operationId": "create_task",
                    "responses": {
                        "201": {
                            "description": "Successful Response"
                        }
                    }
                }
            }
        }
    }, indent=2)

    adr_md = """# Architecture Decision Record (ADR)

## Title: Technology Stack Selection for TaskFlow

## Status: Approved

## Context:
We need a lightweight, production-ready, full-stack tech stack to support the TaskFlow application under the requested requirement.

## Decision:
- **FastAPI** for backend API because of speed, native OpenAPI generation, and ease of deployment.
- **SQLAlchemy** with SQLite/Postgres for robust object-relational mapping.
- **React + Vite** for frontend UI to support quick compile times, robust components, and clean proxy routing.
- **Docker** for containers to ensure standardized build/run boundaries.

## Consequences:
- Easy local setup (single CLI command for docker-compose).
- Low memory consumption.
- Good scalability via Kubernetes replica scaling.
"""

    files = [
        {"path": "README.md",            "content": readme_md},
        {"path": "docs/openapi.json",    "content": openapi_json},
        {"path": "docs/adr/0001-tech-selection.md", "content": adr_md},
    ]

    return {
        "files": files,
        "format": "Markdown + JSON"
    }


def documentation_node(state: ProjectState) -> Dict[str, Any]:
    """
    Documentation Agent Node.

    Input:
        - deployment_manifests (dict)

    Output:
        - api_documentation (dict): Paths and files of generated documentation.
    """
    run_id = state.get("run_id")
    requirement = state.get("business_requirement", "")

    db = SessionLocal()
    db.add(RunEvent(run_id=run_id, agent_name="Documentation Agent", status="STARTED",
                    message="Documentation Agent starting README, OpenAPI, and ADR documentation generation."))
    db.commit()

    doc_data = None
    api_key = os.getenv("ANTHROPIC_API_KEY")
    is_mock = not api_key or api_key.startswith("your-")

    if not is_mock:
        try:
            from langchain_anthropic import ChatAnthropic
            llm = ChatAnthropic(model="claude-3-5-sonnet-20240620", temperature=0)
            structured_llm = llm.with_structured_output(ApiDocs)
            result = structured_llm.invoke(
                f"You are the Documentation Agent. Generate a README.md, openapi.json spec, "
                f"and Architecture Decision Record (ADR) based on this requirement: {requirement}"
            )
            doc_data = result.dict()
        except Exception as e:
            logger.error(f"Documentation Agent LLM failed, using mock: {e}")

    if doc_data is None:
        doc_data = generate_mock_docs(requirement)

    # Write files to disk under generated_projects/{run_id}/docs
    output_dir = os.path.join("generated_projects", run_id, "docs")
    for file_info in doc_data["files"]:
        file_path = os.path.join(output_dir, file_info["path"])
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(file_info["content"])

    try:
        db.add(AgentOutput(run_id=run_id, agent_name="Documentation Agent",
                           artifact_type="api_documentation",
                           content={"path": output_dir,
                                    "files": [f["path"] for f in doc_data["files"]],
                                    "format": doc_data["format"]}))
        db.add(RunEvent(run_id=run_id, agent_name="Documentation Agent", status="COMPLETED",
                        message=f"Generated {len(doc_data['files'])} documentation files in {output_dir}"))
        run_rec = db.query(ProjectRun).filter(ProjectRun.id == run_id).first()
        if run_rec:
            run_rec.current_agent = "Documentation Agent"
        db.commit()
    except Exception as e:
        db.rollback()
        raise e
    finally:
        db.close()

    return {"api_documentation": doc_data}
