import os
import json
import logging
from typing import Dict, Any

from graph.state import ProjectState
from schemas.frontend import FrontendCode
from db.database import SessionLocal
from db.models import AgentOutput, RunEvent, ProjectRun

logger = logging.getLogger(__name__)


def generate_mock_frontend(ux_mockups: Dict, architecture: Dict, requirement: str) -> Dict[str, Any]:
    """
    Generates a complete, runnable React + Vite project structure.
    """
    req_lower = requirement.lower()
    is_task_app = "task" in req_lower or "todo" in req_lower
    app_title = "TaskFlow" if is_task_app else "AppDashboard"

    # --- package.json ---
    package_json = json.dumps({
        "name": app_title.lower(),
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview"
        },
        "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "axios": "^1.6.0"
        },
        "devDependencies": {
            "@vitejs/plugin-react": "^4.0.0",
            "vite": "^5.0.0"
        }
    }, indent=2)

    # --- vite.config.js ---
    vite_config = """\
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:8001',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\\/api/, '')
      }
    }
  }
})
"""

    # --- index.html ---
    index_html = f"""\
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="{app_title} - Generated by ASDT" />
    <title>{app_title}</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""

    # --- src/main.jsx ---
    main_jsx = """\
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './App.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
"""

    # --- src/App.css ---
    app_css = """\
:root {
  --bg: #0f172a;
  --card: rgba(30, 41, 59, 0.7);
  --border: rgba(255, 255, 255, 0.08);
  --primary: #3b82f6;
  --primary-hover: #2563eb;
  --text: #f8fafc;
  --muted: #94a3b8;
  --success: #10b981;
  --warning: #f59e0b;
  --danger: #ef4444;
  --font: 'Outfit', sans-serif;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  background: var(--bg);
  color: var(--text);
  font-family: var(--font);
  min-height: 100vh;
}

.app-layout { display: flex; min-height: 100vh; }

.sidebar {
  width: 260px;
  background: rgba(15,23,42,0.95);
  border-right: 1px solid var(--border);
  padding: 2rem 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 2rem;
  position: fixed;
  height: 100vh;
}

.logo {
  font-size: 1.5rem;
  font-weight: 700;
  background: linear-gradient(135deg, #3b82f6, #8b5cf6);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.nav-list { list-style: none; display: flex; flex-direction: column; gap: 0.5rem; }

.nav-item {
  padding: 0.75rem 1rem;
  border-radius: 0.5rem;
  color: var(--muted);
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.nav-item:hover, .nav-item.active {
  color: var(--text);
  background: rgba(255,255,255,0.05);
}

.main-content {
  flex: 1;
  margin-left: 260px;
  padding: 2.5rem;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 2rem;
}

.page-header h1 { font-size: 2rem; font-weight: 700; }
.page-header p { color: var(--muted); margin-top: 0.25rem; }

.btn {
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 0.5rem;
  font-weight: 600;
  cursor: pointer;
  font-family: var(--font);
  transition: all 0.2s;
}

.btn-primary {
  background: linear-gradient(135deg, var(--primary), var(--primary-hover));
  color: white;
  box-shadow: 0 4px 15px rgba(59,130,246,0.2);
}

.btn-primary:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(59,130,246,0.35); }

.btn-danger { background: rgba(239,68,68,0.1); color: var(--danger); border: 1px solid rgba(239,68,68,0.3); }
.btn-danger:hover { background: rgba(239,68,68,0.2); }

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px,1fr));
  gap: 1.25rem;
  margin-bottom: 2rem;
}

.stat-card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 1rem;
  padding: 1.5rem;
  backdrop-filter: blur(12px);
}

.stat-label { color: var(--muted); font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.08em; }
.stat-value { font-size: 2rem; font-weight: 700; margin-top: 0.25rem; }

.section-title { font-size: 1.25rem; font-weight: 600; margin-bottom: 1rem; }

.task-list { display: flex; flex-direction: column; gap: 0.75rem; }

.task-card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 0.75rem;
  padding: 1.25rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  transition: border-color 0.2s;
}

.task-card:hover { border-color: rgba(59,130,246,0.4); }

.task-title { font-size: 1rem; font-weight: 600; }
.task-desc { color: var(--muted); font-size: 0.85rem; margin-top: 0.2rem; }

.tags { display: flex; gap: 0.4rem; margin-top: 0.4rem; }
.tag {
  background: rgba(255,255,255,0.06);
  padding: 0.15rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.72rem;
  color: var(--muted);
}

.badge {
  padding: 0.3rem 0.7rem;
  border-radius: 2rem;
  font-size: 0.72rem;
  font-weight: 600;
  text-transform: uppercase;
  white-space: nowrap;
}

.badge-high   { background: rgba(239,68,68,0.12); color: var(--danger); }
.badge-medium { background: rgba(245,158,11,0.12); color: var(--warning); }
.badge-low    { background: rgba(16,185,129,0.12); color: var(--success); }

/* Modal */
.modal-overlay {
  position: fixed; inset: 0;
  background: rgba(0,0,0,0.6);
  display: flex; align-items: center; justify-content: center;
  z-index: 100;
}

.modal {
  background: #1e293b;
  border: 1px solid var(--border);
  border-radius: 1rem;
  padding: 2rem;
  width: 480px;
  max-width: 90vw;
}

.modal h2 { font-size: 1.25rem; margin-bottom: 1.5rem; }

.form-group { margin-bottom: 1.25rem; }
.form-group label { display: block; color: var(--muted); font-size: 0.85rem; margin-bottom: 0.4rem; }

.form-input, .form-select {
  width: 100%; padding: 0.7rem 1rem;
  background: rgba(255,255,255,0.05);
  border: 1px solid var(--border);
  border-radius: 0.5rem;
  color: var(--text);
  font-family: var(--font);
  font-size: 0.95rem;
  outline: none;
  transition: border-color 0.2s;
}

.form-input:focus, .form-select:focus { border-color: var(--primary); }
.form-select option { background: #1e293b; }

.modal-actions { display: flex; gap: 1rem; justify-content: flex-end; margin-top: 1.5rem; }

.loading { display: flex; align-items: center; justify-content: center; height: 200px; color: var(--muted); }
.error { color: var(--danger); padding: 1rem; text-align: center; }
"""

    # --- src/api/tasks.js ---
    tasks_api_js = """\
import axios from 'axios'

const BASE = '/api/tasks'

export const getTasks   = ()       => axios.get(BASE)
export const createTask = (data)   => axios.post(BASE, data)
export const updateTask = (id, d)  => axios.put(`${BASE}/${id}`, d)
export const deleteTask = (id)     => axios.delete(`${BASE}/${id}`)
export const completeTask = (id)   => axios.patch(`${BASE}/${id}/complete`)
"""

    # --- src/components/TaskCard.jsx ---
    task_card_jsx = """\
import React from 'react'

export default function TaskCard({ task, onDelete, onComplete }) {
  const badgeClass = {
    High: 'badge-high',
    Medium: 'badge-medium',
    Low: 'badge-low'
  }[task.priority] || 'badge-low'

  return (
    <div className="task-card">
      <div>
        <div className="task-title">{task.title}</div>
        {task.description && <div className="task-desc">{task.description}</div>}
        {task.tags?.length > 0 && (
          <div className="tags">
            {task.tags.map(t => <span key={t} className="tag">{t}</span>)}
          </div>
        )}
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
        <span className={`badge ${badgeClass}`}>{task.priority}</span>
        {task.status !== 'Completed' && (
          <button className="btn btn-primary" style={{ padding: '0.4rem 0.9rem', fontSize: '0.8rem' }}
            onClick={() => onComplete(task.id)}>Done</button>
        )}
        <button className="btn btn-danger" style={{ padding: '0.4rem 0.9rem', fontSize: '0.8rem' }}
          onClick={() => onDelete(task.id)}>Delete</button>
      </div>
    </div>
  )
}
"""

    # --- src/components/StatCard.jsx ---
    stat_card_jsx = """\
import React from 'react'

export default function StatCard({ label, value, color }) {
  return (
    <div className="stat-card">
      <div className="stat-label">{label}</div>
      <div className="stat-value" style={{ color }}>{value}</div>
    </div>
  )
}
"""

    # --- src/components/AddTaskModal.jsx ---
    add_task_modal_jsx = """\
import React, { useState } from 'react'

export default function AddTaskModal({ onClose, onAdd }) {
  const [form, setForm] = useState({ title: '', description: '', priority: 'Medium', tags: '' })

  const handleSubmit = (e) => {
    e.preventDefault()
    if (!form.title.trim()) return
    onAdd({
      ...form,
      tags: form.tags.split(',').map(t => t.trim()).filter(Boolean)
    })
    onClose()
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={e => e.stopPropagation()}>
        <h2>Add New Task</h2>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>Title *</label>
            <input className="form-input" value={form.title}
              onChange={e => setForm({...form, title: e.target.value})}
              placeholder="Task title..." required />
          </div>
          <div className="form-group">
            <label>Description</label>
            <input className="form-input" value={form.description}
              onChange={e => setForm({...form, description: e.target.value})}
              placeholder="Optional description..." />
          </div>
          <div className="form-group">
            <label>Priority</label>
            <select className="form-select" value={form.priority}
              onChange={e => setForm({...form, priority: e.target.value})}>
              <option>High</option>
              <option>Medium</option>
              <option>Low</option>
            </select>
          </div>
          <div className="form-group">
            <label>Tags (comma separated)</label>
            <input className="form-input" value={form.tags}
              onChange={e => setForm({...form, tags: e.target.value})}
              placeholder="e.g. work, urgent" />
          </div>
          <div className="modal-actions">
            <button type="button" className="btn btn-danger" onClick={onClose}>Cancel</button>
            <button type="submit" className="btn btn-primary">Add Task</button>
          </div>
        </form>
      </div>
    </div>
  )
}
"""

    # --- src/App.jsx ---
    app_jsx = f"""\
import React, {{ useState, useEffect }} from 'react'
import TaskCard from './components/TaskCard.jsx'
import StatCard from './components/StatCard.jsx'
import AddTaskModal from './components/AddTaskModal.jsx'
import {{ getTasks, createTask, deleteTask, completeTask }} from './api/tasks.js'

export default function App() {{
  const [tasks, setTasks] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [showModal, setShowModal] = useState(false)
  const [activeNav, setActiveNav] = useState('Dashboard')

  const fetchTasks = async () => {{
    try {{
      const res = await getTasks()
      setTasks(res.data)
    }} catch (err) {{
      setError('Could not load tasks. Make sure the API server is running.')
    }} finally {{
      setLoading(false)
    }}
  }}

  useEffect(() => {{ fetchTasks() }}, [])

  const handleAdd = async (data) => {{
    try {{
      await createTask(data)
      fetchTasks()
    }} catch (err) {{ setError('Failed to create task.') }}
  }}

  const handleDelete = async (id) => {{
    try {{
      await deleteTask(id)
      setTasks(prev => prev.filter(t => t.id !== id))
    }} catch (err) {{ setError('Failed to delete task.') }}
  }}

  const handleComplete = async (id) => {{
    try {{
      await completeTask(id)
      fetchTasks()
    }} catch (err) {{ setError('Failed to update task.') }}
  }}

  const pending   = tasks.filter(t => t.status === 'Pending').length
  const active    = tasks.filter(t => t.status === 'In Progress').length
  const completed = tasks.filter(t => t.status === 'Completed').length

  const navItems = ['Dashboard', 'My Tasks', 'Categories', 'Settings']

  return (
    <div className="app-layout">
      <div className="sidebar">
        <div className="logo">⚡ {app_title}</div>
        <ul className="nav-list">
          {{navItems.map(item => (
            <li key={{item}} className={{`nav-item ${{activeNav === item ? 'active' : ''}}`}}
              onClick={{() => setActiveNav(item)}}>{{item}}</li>
          ))}}
        </ul>
      </div>

      <div className="main-content">
        <div className="page-header">
          <div>
            <h1>Task Dashboard</h1>
            <p>Manage your tasks and stay productive.</p>
          </div>
          <button className="btn btn-primary" onClick={{() => setShowModal(true)}}>+ New Task</button>
        </div>

        <div className="stats-grid">
          <StatCard label="Pending"   value={{pending}}   color="var(--warning)" />
          <StatCard label="Active"    value={{active}}    color="var(--primary)" />
          <StatCard label="Completed" value={{completed}} color="var(--success)" />
          <StatCard label="Total"     value={{tasks.length}} color="var(--text)" />
        </div>

        <div className="section-title">All Tasks</div>

        {{loading && <div className="loading">Loading tasks...</div>}}
        {{error   && <div className="error">{{error}}</div>}}

        <div className="task-list">
          {{tasks.length === 0 && !loading && (
            <div className="loading">No tasks yet. Create your first task!</div>
          )}}
          {{tasks.map(task => (
            <TaskCard key={{task.id}} task={{task}}
              onDelete={{handleDelete}}
              onComplete={{handleComplete}} />
          ))}}
        </div>
      </div>

      {{showModal && <AddTaskModal onClose={{() => setShowModal(false)}} onAdd={{handleAdd}} />}}
    </div>
  )
}}
"""

    files = [
        {"path": "package.json",                   "content": package_json},
        {"path": "vite.config.js",                 "content": vite_config},
        {"path": "index.html",                     "content": index_html},
        {"path": "src/main.jsx",                   "content": main_jsx},
        {"path": "src/App.jsx",                    "content": app_jsx},
        {"path": "src/App.css",                    "content": app_css},
        {"path": "src/api/tasks.js",               "content": tasks_api_js},
        {"path": "src/components/TaskCard.jsx",    "content": task_card_jsx},
        {"path": "src/components/StatCard.jsx",    "content": stat_card_jsx},
        {"path": "src/components/AddTaskModal.jsx","content": add_task_modal_jsx},
    ]

    return {
        "files": files,
        "framework": "React + Vite",
        "install_command": "npm install",
        "dev_command": "npm run dev"
    }


def frontend_node(state: ProjectState) -> Dict[str, Any]:
    """
    Frontend Developer Agent Node.

    Input:
        - ux_mockups (dict): UI designs and component inventory.
        - architecture_spec (dict): Technical architecture choices.

    Output:
        - frontend_code_path (str): Path to generated React/Vite project on disk.

    Failure Mode:
        - Raises ValueError if ux_mockups or architecture_spec is missing.
    """
    run_id = state.get("run_id")
    ux_mockups = state.get("ux_mockups")
    architecture = state.get("architecture_spec")
    requirement = state.get("business_requirement", "")

    if not ux_mockups or not architecture:
        raise ValueError("ux_mockups and architecture_spec are required. Designer and Architect nodes must run first.")

    db = SessionLocal()
    db.add(RunEvent(run_id=run_id, agent_name="Frontend Developer", status="STARTED",
                    message="Frontend Developer Agent starting React project generation."))
    db.commit()

    frontend_data = None
    api_key = os.getenv("ANTHROPIC_API_KEY")
    is_mock = not api_key or api_key.startswith("your-")

    if not is_mock:
        try:
            from langchain_anthropic import ChatAnthropic
            llm = ChatAnthropic(model="claude-3-5-sonnet-20240620", temperature=0)
            structured_llm = llm.with_structured_output(FrontendCode)
            result = structured_llm.invoke(
                f"You are the Frontend Developer Agent. Generate a complete, working React+Vite project "
                f"with all files needed (package.json, vite.config.js, index.html, src/main.jsx, "
                f"src/App.jsx, src/App.css, components, pages) based on this architecture and mockups.\n\n"
                f"Architecture: {architecture}\nMockups: {ux_mockups}"
            )
            frontend_data = result.dict()
        except Exception as e:
            logger.error(f"Frontend Agent LLM failed, using mock: {e}")

    if frontend_data is None:
        frontend_data = generate_mock_frontend(ux_mockups, architecture, requirement)

    # Write files to disk
    output_dir = os.path.join("generated_projects", run_id, "frontend")
    for file_info in frontend_data["files"]:
        file_path = os.path.join(output_dir, file_info["path"])
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(file_info["content"])

    try:
        db.add(AgentOutput(run_id=run_id, agent_name="Frontend Developer",
                           artifact_type="frontend_code",
                           content={"path": output_dir, "files": [f["path"] for f in frontend_data["files"]],
                                    "framework": frontend_data["framework"],
                                    "install_command": frontend_data["install_command"],
                                    "dev_command": frontend_data["dev_command"]}))
        db.add(RunEvent(run_id=run_id, agent_name="Frontend Developer", status="COMPLETED",
                        message=f"Generated {len(frontend_data['files'])} React files in {output_dir}"))
        run_rec = db.query(ProjectRun).filter(ProjectRun.id == run_id).first()
        if run_rec:
            run_rec.current_agent = "Frontend Developer"
        db.commit()
    except Exception as e:
        db.rollback()
        raise e
    finally:
        db.close()

    return {"frontend_code_path": output_dir}
